WebProje/Models/OkulYonetim.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkulYonetim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OkulYonetim()
        {
            this.Ders = new HashSet<Ders>();
        }
    
        public int OkulYonetimID { get; set; }
        public string AdSoyad { get; set; }
        public string Gorevi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ders> Ders { get; set; }
    }
}

WebProje/Controllers/OkulYonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class OkulYonetimController : Controller
    {
        // GET: OkulYonetim
        WebOkulProjeEntities db = new WebOkulProjeEntities();

        public ActionResult Index(string p)
        {
            var degerler = from d in db.OkulYonetim select d;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(o => o.AdSoyad.Contains(p));
            }
            return View(degerler.ToList());
            //var yonetim = db.OkulYonetim.ToList();
            //return View(yonetim);
        }

        [HttpGet]
        public ActionResult YoneticiEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YoneticiEkle(OkulYonetim oy)
        {
            db.OkulYonetim.Add(oy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YoneticiSil(int id)
        {
            var yonetici = db.OkulYonetim.Find(id);
            db.OkulYonetim.Remove(yonetici);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YoneticiGetir(int id)
        {
            var yonetim = db.OkulYonetim.Find(id);
            return View("YoneticiGetir", yonetim);
        }

        public ActionResult YoneticiGuncelle(OkulYonetim oy)
        {
            var yonetici = db.OkulYonetim.Find(oy.OkulYonetimID);
            yonetici.AdSoyad = oy.AdSoyad;
            yonetici.Gorevi = oy.Gorevi;
            db.SaveChanges();
            return RedirectToAction("Index");
                
        }
    }
}

WebProje/Views/OkulYonetim/Index.cshtml
@using WebProje.Models;
@model List<OkulYonetim> 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OkulYonetimLayout.cshtml";
}

@using (Html.BeginForm("Index", "OkulYonetim", FormMethod.Get))
            {
                <p>
                    <b>Aramak istediğiniz Yönetici Adı:</b>@Html.TextBox("p")
                    <input type="submit" value="ARA"/>
                </p>
            }
<table class="table table-bordered">
    <tr>
        <th>Yönetici ID</th>
        <th>Yönetici Adı Soyadı</th>
        <th>Yönetici Görevi</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.OkulYonetimID</td>
                    <td>@x.AdSoyad</td>
                    <td>@x.Gorevi</td>
                    <td><a href="/OkulYonetim/YoneticiSil/@x.OkulYonetimID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/OkulYonetim/YoneticiGetir/@x.OkulYonetimID" class="btn btn-warning">Güncelle</a></td>
                </tr>
            }
</table>
<a href="/OkulYonetim/YoneticiEkle/" class="btn btn-primary">Yeni Yönetici Kaydı</a>

WebProje/Views/OkulYonetim/YoneticiEkle.cshtml
@model WebProje.Models.OkulYonetim
@{
    ViewBag.Title = "YoneticiEkle";
    Layout = "~/Views/Shared/_OkulYonetimLayout.cshtml";
}

<h2>Yeni Yönetici Ekle</h2>
<br />

<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.AdSoyad)
        @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
    </div>

    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Gorevi)
        @Html.TextBoxFor(x => x.Gorevi, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Yöneticiyi Ekle</button>
</form>

WebProje/Views/OkulYonetim/YoneticiGetir.cshtml
@model WebProje.Models.OkulYonetim
@{
    ViewBag.Title = "YoneticiGetir";
    Layout = "~/Views/Shared/_OkulYonetimLayout.cshtml";
}

<h2>Yönetici Güncelle</h2>

@using (Html.BeginForm("YoneticiGuncelle", "OkulYonetim", FormMethod.Post))
{
    <div style="margin-bottom:15px">
        @Html.HiddenFor(y=>y.OkulYonetimID)
        @Html.LabelFor(x => x.AdSoyad)
        @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
    </div>

    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Gorevi)
        @Html.TextBoxFor(x => x.Gorevi, new { @class = "form-control" })
    </div>
    <button class="btn btn-success">Yöneticiyi Güncelle</button>
}