WebProje/Models/Ders.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ders()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int DersID { get; set; }
        public string DersAdi { get; set; }
        public int DersKredisi { get; set; }
        public int OkulYonetimID { get; set; }
    
        public virtual OkulYonetim OkulYonetim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}

WebProje/Controllers/DersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class DersController : Controller
    {
        // GET: Ders

        WebOkulProjeEntities db = new WebOkulProjeEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.Ders select d;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(o => o.DersAdi.Contains(p));
            }
            return View(degerler.ToList());
            //var dersler = db.Ders.ToList();
            //return View(dersler);
        }
        [HttpGet]
        public ActionResult DersEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DersEkle(Ders d)
        {
            var db = new WebOkulProjeEntities();
            db.Ders.Add(d);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DersSil(int id)
        {
            var ders = db.Ders.Find(id);
            db.Ders.Remove(ders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DersGetir(int id)
        {
            var ders = db.Ders.Find(id);
            return View("DersGetir", ders);
        }
        public ActionResult DersGuncelle(Ders d)
        {
            var ders = db.Ders.Find(d.DersID);
            ders.DersAdi = d.DersAdi;
            ders.DersKredisi = d.DersKredisi;
            ders.OkulYonetim.AdSoyad = d.OkulYonetim.AdSoyad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebProje/Views/Ders/DersEkle.cshtml
@model WebProje.Models.Ders
@{
    ViewBag.Title = "DersEkle";
    Layout = "~/Views/Shared/_DersLayout.cshtml";
}

<h2>Yeni Ders Ekle</h2>
<br />

<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.DersAdi)
        @Html.TextBoxFor(x=>x.DersAdi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.DersKredisi)
        @Html.TextBoxFor(x=>x.DersKredisi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OkulYonetimID)
        @Html.TextBoxFor(x => x.OkulYonetimID, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Ders Ekle</button>
</form>

WebProje/Views/Ders/DersGetir.cshtml
@model WebProje.Models.Ders
@{
    ViewBag.Title = "DersGetir";
    Layout = "~/Views/Shared/_DersLayout.cshtml";
}

<h2>Ders Güncelle</h2>
<br />

@using (Html.BeginForm("DersGuncelle", "Ders", FormMethod.Post))
            {
                <div style="margin-bottom:15px">
                    @Html.HiddenFor(y=>y.DersID)
                    @Html.LabelFor(x => x.DersAdi)
                    @Html.TextBoxFor(x=>x.DersAdi, new { @class = "form-control" })
                </div>
                <div style="margin-bottom:15px">
                    @Html.LabelFor(x => x.DersKredisi)
                    @Html.TextBoxFor(x=>x.DersKredisi, new { @class = "form-control" })
                </div>
                <div style="margin-bottom:15px">
                    @Html.LabelFor(x => x.OkulYonetim.AdSoyad)
                    @Html.TextBoxFor(x=>x.OkulYonetim.AdSoyad, new { @class = "form-control" })
                </div>
                <button class="btn btn-success">Dersi Güncelle</button>
            }

WebProje/Views/Ders/Index.cshtml
@using WebProje.Models;
@model List<Ders> 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DersLayout.cshtml";
}

@using (Html.BeginForm("Index", "Ders", FormMethod.Get))
            {
                <p>
                    <b>Aramak istediğiniz Ders Adı:</b>@Html.TextBox("p")
                    <input type="submit" value="ARA"/>
                </p>
            }

<table class="table table-bordered">
    <tr>
        <th>Ders ID</th>
        <th>Dersin Adı</th>
        <th>Dersin Kredisi</th>
        <th>Dersin Yöneticisi</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.DersID</td>
                    <td>@x.DersAdi</td>
                    <td>@x.DersKredisi</td>
                    <td>@x.OkulYonetim.AdSoyad</td>
                    <td><a href="/Ders/DersSil/@x.DersID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Ders/DersGetir/@x.DersID" class="btn btn-warning">Güncelle</a></td>
                </tr>
            }
</table>
<a href="/Ders/DersEkle/" class="btn btn-primary">Yeni Ders Ekle</a>