WebProje/Models/OgrenciDers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciDers
    {
        public int ID { get; set; }
        public int DersID { get; set; }
        public int OgrenciID { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}

WebProje/Controllers/OgrenciDersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class OgrenciDersController : Controller
    {
        // GET: OgrenciDers

        WebOkulProjeEntities db = new WebOkulProjeEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.OgrenciDers select d;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(o => o.Ders.DersAdi.Contains(p));
            }
            return View(degerler.ToList());
            //var ogrd = db.OgrenciDers.ToList();
            //return View(ogrd);
        }

        [HttpGet]
        public ActionResult OgrenciDersEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OgrenciDersEkle(OgrenciDers ogrd)
        {
            var db = new WebOkulProjeEntities();
            db.OgrenciDers.Add(ogrd);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult OgrenciDersSil(int id)
        {
            var ogrders = db.OgrenciDers.Find(id);
            db.OgrenciDers.Remove(ogrders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult OgrenciDersGetir(int id)
        {
            var ogrders = db.OgrenciDers.Find(id);
            return View("OgrenciDersGetir", ogrders);
        }
        public ActionResult OgrenciDersiGuncelle(OgrenciDers ogrd)
        {
            var ogr = db.OgrenciDers.Find(ogrd.ID);
            ogr.Ders.DersAdi = ogrd.Ders.DersAdi;
            ogr.Ogrenci.OgrenciAdiSoyadi = ogrd.Ogrenci.OgrenciAdiSoyadi;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebProje/Views/OgrenciDers/Index.cshtml
@using WebProje.Models
@model List<OgrenciDers>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OgrenciDersLayout.cshtml";
}

@using (Html.BeginForm("Index", "OgrenciDers", FormMethod.Get))
            {
                <p>
                    <b>Aramak istediğiniz Ders:</b> @Html.TextBox("p")
                    <input type="submit" value="ARA" />
                </p>
            }

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ders ID</th>
        <th>Öğrenci ID</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.ID</td>
                    <td>@x.Ders.DersAdi</td>
                    <td>@x.Ogrenci.OgrenciAdiSoyadi</td>
                    <td><a href="/OgrenciDers/OgrenciDersSil/@x.ID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/OgrenciDers/OgrenciDersGetir/@x.ID" class="btn btn-warning">Güncelle</a></td>
                </tr>
            }
</table>
<a href="/OgrenciDers/OgrenciDersEkle/" class="btn btn-primary">Yeni Öğrenci Dersi</a>

WebProje/Views/OgrenciDers/OgrenciDersEkle.cshtml
@model WebProje.Models.OgrenciDers
@{
    ViewBag.Title = "OgrenciDersEkle";
    Layout = "~/Views/Shared/_OgrenciDersLayout.cshtml";
}

<h2>Yeni Öğrenci Dersi Ekle</h2>
<br />

<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.DersID)
        @Html.TextBoxFor(x => x.DersID, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciID)
        @Html.TextBoxFor(x => x.OgrenciID, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Yeni Öğrenci Ders</button>
</form>

WebProje/Views/OgrenciDers/OgrenciDersGetir.cshtml
@model WebProje.Models.OgrenciDers
@{
    ViewBag.Title = "OgrenciDersGetir";
    Layout = "~/Views/Shared/_OgrenciDersLayout.cshtml";
}

<h2>Öğrencinin Dersini Güncelle</h2>
<br />

@using(Html.BeginForm("OgrenciDersiGuncelle", "OgrenciDers", FormMethod.Post))
            {
                <div style="margin-bottom:15px">
                    @Html.HiddenFor(y => y.ID)
                    @Html.LabelFor(x => x.Ders.DersAdi)
                    @Html.TextBoxFor(x => x.Ders.DersAdi, new { @class = "form-control" })
                </div>
                <div style="margin-bottom:15px">
                    @Html.LabelFor(x => x.Ogrenci.OgrenciAdiSoyadi)
                    @Html.TextBoxFor(x => x.Ogrenci.OgrenciAdiSoyadi, new { @class = "form-control" })
                </div>
                <button class="btn btn-success">Öğrenci Dersi Güncelle</button>
            }