WebProje/Models/Ogrenci.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int OgrenciID { get; set; }
        public string OgrenciAdiSoyadi { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public System.DateTime OgrenciDogumTarihi { get; set; }
        public System.DateTime OgrenciKayitTarihi { get; set; }
        public string OgrenciBolumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}

WebProje/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci

        WebOkulProjeEntities db = new WebOkulProjeEntities();

        public ActionResult Index(string p)
        {
            var degerler = from d in db.Ogrenci select d;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(o => o.OgrenciAdiSoyadi.Contains(p));
            }
            return View(degerler.ToList());
            //var ogrenciler = db.Ogrenci.ToList();
            //return View(ogrenciler);
        }

        [HttpGet]
        public ActionResult OgrenciEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OgrenciEkle(Ogrenci o)
        {
            db.Ogrenci.Add(o);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciSil(int id)
        {
            var ogrenci = db.Ogrenci.Find(id);
            db.Ogrenci.Remove(ogrenci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciGetir(int id)
        {
            var ogr = db.Ogrenci.Find(id);
            return View("OgrenciGetir", ogr);
        }

        public ActionResult OgrenciGuncelle(Ogrenci o)
        {
            var ogrenci = db.Ogrenci.Find(o.OgrenciID);
            ogrenci.OgrenciAdiSoyadi = o.OgrenciAdiSoyadi;
            ogrenci.OgrenciNo = o.OgrenciNo;
            ogrenci.OgrenciDogumTarihi = o.OgrenciDogumTarihi;
            ogrenci.OgrenciKayitTarihi = o.OgrenciKayitTarihi;
            ogrenci.OgrenciBolumu = o.OgrenciBolumu;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebProje/Views/Ogrenci/Index.cshtml
@using WebProje.Models;
@model List<Ogrenci>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

@using (Html.BeginForm("Index", "Ogrenci", FormMethod.Get))
            {
                <p>
                    <b>Aramak istediğiniz Öğrenci Adı:</b> @Html.TextBox("p")
                    <input type="submit" value="ARA"/>
                </p>
            }
<table class="table table-bordered">
    <tr>
        <th>Öğrenci ID</th>
        <th>Öğrenci Adı Soyadı</th>
        <th>Öğrenci No</th>
        <th>Öğrenci Doğum Tarihi</th>
        <th>Öğrenci Kayıt Tarihi</th>
        <th>Öğrenci Bölümü</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.OgrenciID</td>
                    <td>@x.OgrenciAdiSoyadi</td>
                    <td>@x.OgrenciNo</td>
                    <td>@x.OgrenciDogumTarihi</td>
                    <td>@x.OgrenciKayitTarihi</td>
                    <td>@x.OgrenciBolumu</td>
                    <td><a href="/Ogrenci/OgrenciSil/@x.OgrenciID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Ogrenci/OgrenciGetir/@x.OgrenciID" class="btn btn-warning">Güncelle</a></td>
                </tr>
            }
</table>
<a href="/Ogrenci/OgrenciEkle/" class="btn btn-primary">Yeni Öğrenci Kaydı</a>

WebProje/Views/Ogrenci/OgrenciEkle.cshtml
@model WebProje.Models.Ogrenci
@{
    ViewBag.Title = "OgrenciEkle";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2>Öğrenci Ekle</h2>
<br />

<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciAdiSoyadi)
        @Html.TextBoxFor(x => x.OgrenciAdiSoyadi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciNo)
        @Html.TextBoxFor(x => x.OgrenciNo, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciDogumTarihi)
        @Html.TextBoxFor(x => x.OgrenciDogumTarihi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciKayitTarihi)
        @Html.TextBoxFor(x => x.OgrenciKayitTarihi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciBolumu)
        @Html.TextBoxFor(x => x.OgrenciBolumu, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Öğrenci Ekle</button>
</form>

WebProje/Views/Ogrenci/OgrenciGetir.cshtml
@model WebProje.Models.Ogrenci
@{
    ViewBag.Title = "OgrenciGetir";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2>Öğrenci Güncelle</h2>
<br />

@using (Html.BeginForm("OgrenciGuncelle", "Ogrenci", FormMethod.Post))
{
    <div style="margin-bottom:15px">
        @Html.HiddenFor(y => y.OgrenciID)
        @Html.LabelFor(x => x.OgrenciAdiSoyadi)
        @Html.TextBoxFor(x => x.OgrenciAdiSoyadi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciNo)
        @Html.TextBoxFor(x => x.OgrenciNo, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciDogumTarihi)
        @Html.TextBoxFor(x => x.OgrenciDogumTarihi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciKayitTarihi)
        @Html.TextBoxFor(x => x.OgrenciKayitTarihi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciBolumu)
        @Html.TextBoxFor(x => x.OgrenciBolumu, new { @class = "form-control" })
    </div>
    <button class="btn btn-success">Öğrenci Güncelle</button>
}